name: Build and Deploy Coffee App to Azure

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

env:
  AZURE_WEBAPP_NAME: mycoffeeappweb # Replace with your Azure Web App name
  ACR_REGISTRY_NAME: mycoffeeappregistry # Replace with your Azure Container Registry name
  IMAGE_NAME: coffee-app # Name of your Docker image

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ACR_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          VCS_REF=${{ github.sha }}

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
